[package]
name = "linkchecker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.12", features = ["derive", "cargo"] }
reqwest = { version = "0.11", features = ["json"] }
futures = "0.3"
tokio = { version = "1.12.0", features = ["full"] }
assert_cli = "0.6.3"
